name: Playwright Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to use'
        required: true
        default: 'chromium'
        options:
          - chromium
          - firefox
          - webkit
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        working-directory: ./app

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npm run test
